version: '2'
services:
  mongo:
    image: "mongo:3.0"
    ports:
      - "27017:27017"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  storage:
    build: https://github.com/webautotester/storage.git
    image: "xblanc/wat_storage"
    ports:
      - "8085:8085"
    depends_on:
      - "mongo"
  scheduler:
    build: https://github.com/webautotester/scheduler.git
    image: "xblanc/wat_scheduler"
    ports:
      - "8090:8090"
    depends_on:
      - "rabbit"
      - "mongo"
  front:
    build: https://github.com/webautotester/front.git
    image: "xblanc/wat_front"
    ports:
      - "8080:8080"
    depends_on:
      - "rabbit"
      - "mongo"
  player1:
    build: https://github.com/webautotester/player.git
    image: "xblanc/wat_player"
    depends_on:
      - "rabbit"
      - "mongo"
  player2:
    build: https://github.com/webautotester/player.git
    image: "xblanc/wat_player"
    depends_on:
      - "rabbit"
      - "mongo"
